config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  
  resources :products, only: [:index, :show, :new, :create] do
    resources :charges, only: [:create]
  end  

  post '/create_checkout_session', to: 'products#create_checkout_session'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def create
      @product = Product.find(params[:product_id])
      @amount = @product.price * 100
  
      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )
  
      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: @product.name,
        currency: 'usd'
      )
  
      flash[:success] = "Payment successful!"
      redirect_to product_path(@product)
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to product_path(@product)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'styles', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<!-- app/views/products/index.html.erb -->
<div class="container">
<h1>All Products</h1>

<%= link_to "Add New Product", new_product_path, class: "btn btn-success mb-3" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to "View Details", product_path(product), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/products/new.html.erb
<!-- app/views/products/new.html.erb -->

<div class="container">
  
<h1>Add New Product</h1>

<%= form_with(model: @product, url: products_path, method: :post) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <%= form.submit "Create Product", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to all products", products_path, class: "btn btn-secondary mt-3" %>

</div>

app/views/products/show.html.erb
<!-- app/views/products/show.html.erb -->

<div class="container">
  
<h1><%= @product.name %></h1>
<p>Price: <%= @product.price %></p>

<%= form_tag product_charges_path(@product) do %>
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.application.credentials.stripe[:publishable_key] %>"
    data-amount="<%= @product.price * 100 %>"
    data-name="Stripe Ecommerce"
    data-description="<%= @product.name %>"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
<% end %>

<%= link_to "Back to all products", products_path %>
</div>